namespace DecoratorPattern.Beverages
{
    public enum DrinkType
    {
        Espresso,
        Doppio,
        Lungo,
        Macchiato,
        Corretta,
        ConPanna,
        Cappuccino,
        Americano,
        CaffeLatte,
        FlatWhite,
        Romana,
        Marocchino,
        Mocha,
        Bicerin,
        Breve,
        RafCoffee,
        MeadRaf,
        Galao,
        CaffeAffogato,
        ViennaCoffee,
        Glace,
        ChocolateMilk,
        DemiCreme,
        LatteMacchiato,
        Freddo,
        Frappuccino,
        CaramelFrappuccino,
        Frappe,
        IrishCoffee
    }
}
